---
title: "Data import - Metabotandem"
author: "Christian Ayala"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

# 1. Importing libraries

Make sure `xcms` is installed.

```{r}
library(xcms)
library(tidyverse)
```

# 2. Import data

**Important** Data was already in centroid mode.

```{r}

# define metadata, ie, phenotypic data
data_dir <- '../../data/'
metadata_file <- '../../data/metadata.csv'

# Open metadata
pd <- read.csv(metadata_file)

# Get list of mass spectra files
ms_files <- list.files(data_dir, full.names = TRUE, pattern = '*.mzXML')

# Read the data:
data_cent <- readMSData(ms_files, 
                        pdata = new("NAnnotatedDataFrame", pd), 
                        mode = "onDisk",
                        verbose = TRUE)
```

The MS experiment is now represented as an `OnDiskMSnExp` object. 

Information stored in the `OnDiskMSnExp` object after import:
```{r}
show(data_cent)
```

Check if data is centroided:

```{r}
prelim <- fData(data_cent)[1:100,]
unique(fData(data_cent)$centroided)
```

# 3. Save R object as `.RData`

Save as an R object so later, you don't need to re-import the data
```{r}
## Save data object as rds

save_file <- file.path('data', 'data_centroided.RData')

save_file <- file.path('..', 'data', 'data_centroided.RData')

save(data_cent, pd, files, file = save_file)
```

